spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
        - id: content-service-posts
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/posts/**
        - id: content-service-reports
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/reports
        - id: rank-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/rank/**
        - id: audit-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/audit/**

server:
  port: 8080